# Generated by Django 4.1 on 2022-11-14 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaible',
            new_name='is_available',
        ),
    ]
