# Generated by Django 4.1 on 2023-08-21 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productGallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
